name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Echo name
        run: echo "Danyal is my name"

      - name: Set up SSH
        run: |
          # Check if .ssh directory exists, create if it does not
          if (-Not (Test-Path -Path $env:USERPROFILE\.ssh)) {
            New-Item -ItemType Directory -Path $env:USERPROFILE\.ssh
          }

          # Save the SSH private key to a file
          $privateKey = "${{ secrets.SSH_PRIVATE_KEY }}"
          $privateKey | Out-File -FilePath "$env:USERPROFILE\.ssh\id_rsa" -Encoding ascii

          # Set the correct permissions on the private key file
          icacls "$env:USERPROFILE\.ssh\id_rsa" /inheritance:r /grant $env:USERNAME:F /c

          # Start the ssh-agent service and add the private key
          if (-Not (Get-Service -Name ssh-agent).Status -eq 'Running') {
            Start-Service ssh-agent
          }
          ssh-add $env:USERPROFILE\.ssh\id_rsa

      - name: SSH and create file on the target server
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-54-92-210-164.compute-1.amazonaws.com "echo 'Danyal is my name' > /home/ec2-user/file.txt"
        shell: bash
