name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Echo name
        run: echo "Danyal is my name"

      - name: Set up SSH
        run: |
          $sshPath = "C:\Users\Administrator\.ssh"
          if (-Not (Test-Path -Path $sshPath)) {
            New-Item -ItemType Directory -Path $sshPath
          }
          Set-Content -Path "$sshPath\id_rsa" -Value "${{ secrets.SSH_PRIVATE_KEY }}"
          $env:GIT_SSH_COMMAND = "ssh -o StrictHostKeyChecking=no -i $sshPath\id_rsa"

      - name: SSH and create file on the target server
        run: |
          ssh ec2-user@ec2-54-92-210-164.compute-1.amazonaws.com "echo 'Danyal is my name' > /home/ec2-user/file.txt"
