name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Echo name
        run: echo "Danyal is my name"

      - name: Set up SSH
        run: |
          $sshPath = "C:\Users\Administrator\.ssh"
          if (-Not (Test-Path -Path $sshPath)) {
            New-Item -ItemType Directory -Path $sshPath
          }
          Set-Content -Path "$sshPath\id_rsa" -Value "${{ secrets.SSH_PRIVATE_KEY }}"
          icacls $sshPath\id_rsa /inheritance:r /grant:r "Administrator:F"
          $env:GIT_SSH_COMMAND = "ssh -o StrictHostKeyChecking=no -i $sshPath\id_rsa"
        shell: powershell

      - name: SSH and create file on the target Windows server
        run: |
          ssh -i C:\Users\Administrator\.ssh\id_rsa -o StrictHostKeyChecking=no administrator@ec2-54-159-248-34.compute-1.amazonaws.com powershell.exe -Command "echo 'Danyal is my name' > C:\Users\Administrator\file.txt"
        shell: bash
