name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Echo name
        run: echo "Danyal is my name"

      - name: Set up SSH
        run: |
          if (-Not (Test-Path -Path $env:USERPROFILE\.ssh)) {
            New-Item -ItemType Directory -Path $env:USERPROFILE\.ssh
          }
          $privateKey = "${{ secrets.SSH_PRIVATE_KEY }}"
          $privateKey | Out-File -FilePath "$env:USERPROFILE\.ssh\id_rsa" -Encoding ascii
          icacls "$env:USERPROFILE\.ssh\id_rsa" /inheritance:r /grant:r $env:USERNAME:F /c
          Start-Service ssh-agent
          ssh-add $env:USERPROFILE\.ssh\id_rsa

      - name: SSH and create file on the target server
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-54-92-210-164.compute-1.amazonaws.com "echo 'Danyal is my name' > /home/ec2-user/file.txt"
        shell: bash
